//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZNGN.TTT.Api.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Application
    {
        public Application()
        {
            this.Session = new HashSet<Session>();
            this.User = new HashSet<User>();
            this.Score = new HashSet<Score>();
        }
    
        public long ID { get; set; }
        public string Name { get; set; }
        public string ApiKey { get; set; }
        public int Status { get; set; }
    
        public virtual ICollection<Session> Session { get; set; }
        public virtual ICollection<User> User { get; set; }
        public virtual ICollection<Score> Score { get; set; }
    }
}
