//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZNGN.TTT.Api.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Score
    {
        public long ID { get; set; }
        public long ApplicationID { get; set; }
        public long UserID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public decimal ScoreValue { get; set; }
    
        public virtual Application Application { get; set; }
        public virtual User User { get; set; }
    }
}
