//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZNGN.TTT.Api.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Session = new HashSet<Session>();
            this.Score = new HashSet<Score>();
        }
    
        public long ID { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Email { get; set; }
        public long ApplicationID { get; set; }
    
        public virtual Application Application { get; set; }
        public virtual ICollection<Session> Session { get; set; }
        public virtual ICollection<Score> Score { get; set; }
    }
}
